/**
 * Copyright(c) Live2D Inc. All rights reserved.
 *
 * Use of this source code is governed by the Live2D Open Software license
 * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.
 */


#include "Model/CubismModelComponent.h"

#include "CubismUpdateExecutionOrder.h"
#include "Model/CubismMoc3.h"
#include "Model/CubismDrawableComponent.h"
#include "Model/CubismParameterComponent.h"
#include "Model/CubismPartComponent.h"
#include "Model/CubismParameterStoreComponent.h"
#include "Rendering/CubismRendererComponent.h"
#include "Motion/CubismMotionComponent.h"
#include "Expression/CubismExpressionComponent.h"
#include "Physics/CubismPhysicsComponent.h"
#include "Pose/CubismPoseComponent.h"
#include "Effects/EyeBlink/CubismEyeBlinkComponent.h"
#include "Effects/HarmonicMotion/CubismHarmonicMotionComponent.h"
#include "Effects/LipSync/CubismLipSyncComponent.h"
#include "Effects/LookAt/CubismLookAtComponent.h"
#include "Effects/Raycast/CubismRaycastComponent.h"
#include "UserData/CubismUserData3Json.h"
#include "Model/CubismParameterStoreComponent.h"
#include "Rendering/CubismRendererComponent.h"
#include "Pose/CubismPoseComponent.h"
#include "Motion/CubismMotionComponent.h"
#include "Expression/CubismExpressionComponent.h"
#include "Physics/CubismPhysicsComponent.h"
#include "Effects/EyeBlink/CubismEyeBlinkComponent.h"
#include "Effects/HarmonicMotion/CubismHarmonicMotionComponent.h"
#include "Effects/LipSync/CubismLipSyncComponent.h"
#include "Effects/LookAt/CubismLookAtComponent.h"

#include "CubismLog.h"
#include "CubismUpdateControllerComponent.h"
#include "UObject/UObjectThreadContext.h"

namespace
{
	/** Small RAII helper to flip a bool for the duration of a scope. */
	struct FScopedBoolFlag
	{
		bool& Flag;
		bool PreviousValue;

		explicit FScopedBoolFlag(bool& InFlag)
			: Flag(InFlag)
			, PreviousValue(InFlag)
		{
			Flag = true;
		}

		~FScopedBoolFlag()
		{
			Flag = PreviousValue;
		}
	};
}

UCubismModelComponent::UCubismModelComponent()
	: RawModel(nullptr)
{
	PrimaryComponentTick.bCanEverTick = true;
	PrimaryComponentTick.TickGroup = TG_PrePhysics;
	bTickInEditor = true;
}

UCubismModelComponent::~UCubismModelComponent()
{
}

UCubismModelComponent* UCubismModelComponent::FindModelComponent(const UActorComponent* Component)
{
	if (!Component)
	{
		return nullptr;
	}

	// Components generated by the model (drawables, parameters, helper components) live inside the model component.
	if (UCubismModelComponent* OuterModel = Component->GetTypedOuter<UCubismModelComponent>())
	{
		return OuterModel;
	}

	const AActor* Owner = Component->GetOwner();

	if (!Owner)
	{
		return nullptr;
	}

	return Owner->FindComponentByClass<UCubismModelComponent>();
}

void UCubismModelComponent::Setup()
{
	if (IsTemplate())
	{
		return;
	}

	// Tear down everything generated from the previous moc and build it again from the current one.
	ComponentCleanup(false);
	ReleaseRawModel();

	if (!Moc)
	{
		return;
	}

	EnsureModelBuilt();
}

bool UCubismModelComponent::EnsureModelBuilt()
{
	if (bIsBuilding || IsTemplate())
	{
		return RawModel != nullptr;
	}

	FScopedBoolFlag BuildingGuard(bIsBuilding);

	if (!Moc)
	{
		return false;
	}

	// The moc was swapped (e.g. from Blueprint) without calling Setup(): the generated components belong to the old one.
	if (RawModel && BuiltMoc != Moc)
	{
		ComponentCleanup(false);
		ReleaseRawModel();
	}

	if (!RawModel)
	{
		Moc->SetupModel(this);

		if (!RawModel)
		{
			UE_LOG(LogCubism, Error, TEXT("UCubismModelComponent::EnsureModelBuilt: failed to create a model from moc '%s'."), *Moc->GetName());

			return false;
		}

		BuiltMoc = Moc;
	}

	bool bChildComponentsRecreated = false;

	if (!ChildComponentsMatchModel())
	{
		// Either nothing has been generated yet, or the generated components belong to a different moc.
		if (!CanCreateComponents())
		{
			// Creating and registering components is not possible while loading; it is retried on registration.
			return true;
		}

		ComponentCleanup(false);
		CreateChildComponents();

		bChildComponentsRecreated = true;
	}

	SetupChildComponents();

	ComponentSetup();

	if (bChildComponentsRecreated)
	{
		// The helper components cache drawables, parameters and parts; they must resolve them again.
		SetupHelperComponents();
	}

	return true;
}

bool UCubismModelComponent::CanCreateComponents() const
{
	if (IsTemplate() || !GetWorld())
	{
		return false;
	}

	// Never spawn and register components while objects are being loaded or duplicated.
	if (HasAnyFlags(RF_NeedLoad | RF_NeedPostLoad) || FUObjectThreadContext::Get().IsRoutingPostLoad)
	{
		return false;
	}

	return true;
}

void UCubismModelComponent::ReleaseRawModel()
{
	if (RawModel)
	{
		if (Moc)
		{
			Moc->DeleteModel(this);
		}
		else
		{
			FMemory::Free(RawModel);
			RawModel = nullptr;
		}
	}

	BuiltMoc = nullptr;
}

bool UCubismModelComponent::ChildComponentsMatchModel() const
{
	if (!RawModel)
	{
		return false;
	}

	const int32 DrawableCount = GetDrawableCount();
	const int32 ParameterCount = GetParameterCount();
	const int32 PartCount = GetPartCount();

	if (Drawables.Num() != DrawableCount || Parameters.Num() < ParameterCount || Parts.Num() < PartCount)
	{
		return false;
	}

	for (int32 DrawableIndex = 0; DrawableIndex < DrawableCount; DrawableIndex++)
	{
		const UCubismDrawableComponent* Drawable = Drawables[DrawableIndex];

		if (!IsValid(Drawable) || Drawable->Index != DrawableIndex || Drawable->Id != GetDrawableId(DrawableIndex))
		{
			return false;
		}
	}

	for (int32 ParameterIndex = 0; ParameterIndex < Parameters.Num(); ParameterIndex++)
	{
		const UCubismParameterComponent* Parameter = Parameters[ParameterIndex];

		if (!IsValid(Parameter) || Parameter->Index != ParameterIndex)
		{
			return false;
		}

		if (ParameterIndex < ParameterCount)
		{
			if (Parameter->Id != GetParameterId(ParameterIndex))
			{
				return false;
			}
		}
		else if (!NonNativeParameterIds.Contains(ParameterIndex))
		{
			return false;
		}
	}

	for (int32 PartIndex = 0; PartIndex < Parts.Num(); PartIndex++)
	{
		const UCubismPartComponent* Part = Parts[PartIndex];

		if (!IsValid(Part) || Part->Index != PartIndex)
		{
			return false;
		}

		if (PartIndex < PartCount)
		{
			if (Part->Id != GetPartId(PartIndex))
			{
				return false;
			}
		}
		else if (!NonNativePartIds.Contains(PartIndex))
		{
			return false;
		}
	}

	return true;
}

void UCubismModelComponent::CreateChildComponents()
{
	check(RawModel);

	AActor* Owner = GetOwner();

	{
		const int32 DrawableCount = GetDrawableCount();
		Drawables.Reserve(DrawableCount);

		for (int32 DrawableIndex = 0; DrawableIndex < DrawableCount; DrawableIndex++)
		{
			const FString DrawableId = GetDrawableId(DrawableIndex);
			DrawableIndices.Add(DrawableId, DrawableIndex);

			const FName ComponentName = MakeUniqueObjectName(this, UCubismDrawableComponent::StaticClass(), FName(*DrawableId));
			UCubismDrawableComponent* Drawable = NewObject<UCubismDrawableComponent>(this, ComponentName, RF_Transactional);

			Drawable->Index = DrawableIndex;

			Drawable->RegisterComponent();
			if (Owner)
			{
				Owner->AddInstanceComponent(Drawable);
			}
			Drawable->AttachToComponent(this, FAttachmentTransformRules::KeepRelativeTransform);

			Drawables.Add(Drawable);
		}
	}

	{
		const int32 ParameterCount = GetParameterCount();
		Parameters.Reserve(ParameterCount);

		for (int32 ParameterIndex = 0; ParameterIndex < ParameterCount; ParameterIndex++)
		{
			const FString ParameterId = GetParameterId(ParameterIndex);
			ParameterIndices.Add(ParameterId, ParameterIndex);

			const FName ComponentName = MakeUniqueObjectName(this, UCubismParameterComponent::StaticClass(), FName(*ParameterId));
			UCubismParameterComponent* Parameter = NewObject<UCubismParameterComponent>(this, ComponentName, RF_Transactional);

			Parameter->Index = ParameterIndex;

			Parameter->RegisterComponent();

			Parameters.Add(Parameter);
		}
	}

	{
		const int32 PartCount = GetPartCount();
		Parts.Reserve(PartCount);

		for (int32 PartIndex = 0; PartIndex < PartCount; PartIndex++)
		{
			const FString PartId = GetPartId(PartIndex);
			PartIndices.Add(PartId, PartIndex);

			const FName ComponentName = MakeUniqueObjectName(this, UCubismPartComponent::StaticClass(), FName(*PartId));
			UCubismPartComponent* Part = NewObject<UCubismPartComponent>(this, ComponentName, RF_Transactional);

			Part->Index = PartIndex;

			Part->RegisterComponent();

			Parts.Add(Part);
		}
	}
}

void UCubismModelComponent::SetupChildComponents()
{
	for (const TObjectPtr<UCubismDrawableComponent>& Drawable : Drawables)
	{
		if (IsValid(Drawable))
		{
			Drawable->Setup(this);
		}
	}

	for (const TObjectPtr<UCubismParameterComponent>& Parameter : Parameters)
	{
		if (IsValid(Parameter))
		{
			Parameter->Setup(this);
		}
	}

	for (const TObjectPtr<UCubismPartComponent>& Part : Parts)
	{
		if (IsValid(Part))
		{
			Part->Setup(this);
		}
	}

	SetVisibility(bRenderInWorldSpace, true);

	SetOverrideFlagForModelParameterRepeat(bOverrideParameterRepeat);
}

void UCubismModelComponent::SetupHelperComponents()
{
	// Order matters: the parameter store must be registered on the model before the components that depend on it.
	if (IsValid(ParameterStore))
	{
		ParameterStore->Setup(this);
	}

	if (IsValid(Motion))
	{
		Motion->Setup(this);
	}

	if (IsValid(Pose))
	{
		Pose->Setup(this);
	}

	if (IsValid(Expression))
	{
		Expression->Setup(this);
	}

	if (IsValid(Physics))
	{
		Physics->Setup(this);
	}

	if (IsValid(EyeBlink))
	{
		EyeBlink->Setup(this);
	}

	if (IsValid(HarmonicMotion))
	{
		HarmonicMotion->Setup(this);
	}

	if (IsValid(LipSync))
	{
		LipSync->Setup(this);
	}

	if (IsValid(LookAt))
	{
		LookAt->Setup(this);
	}

	if (IsValid(Renderer))
	{
		Renderer->Setup(this);
	}

	// The helper components may have been created after the update controller scanned the actor.
	UCubismUpdateControllerComponent::RequestRefresh(this);
}

template<class T>
T* UCubismModelComponent::CreateHelperComponent(TObjectPtr<T>& Reference, const TCHAR* BaseName)
{
	if (IsValid(Reference))
	{
		return Reference;
	}

	const FName ComponentName = MakeUniqueObjectName(this, T::StaticClass(), FName(BaseName));
	T* Component = NewObject<T>(this, T::StaticClass(), ComponentName, RF_Transactional);

	// Assign before registering so that the component's own Setup sees itself as the active one.
	Reference = Component;

	return Component;
}

////

FVector2D UCubismModelComponent::GetCanvasSize() const
{
	if (!RawModel)
	{
		return FVector2D::ZeroVector;
	}

	float PixelsPerUnit;
	csmVector2 CanvasSize, CanvasOrigin;

	csmReadCanvasInfo(RawModel, &CanvasSize, &CanvasOrigin, &PixelsPerUnit);

	return FVector2D(CanvasSize.X, CanvasSize.Y);
}

FVector2D UCubismModelComponent::GetCanvasOrigin() const
{
	if (!RawModel)
	{
		return FVector2D::ZeroVector;
	}

	float PixelsPerUnit;
	csmVector2 CanvasSize, CanvasOrigin;

	csmReadCanvasInfo(RawModel, &CanvasSize, &CanvasOrigin, &PixelsPerUnit);

	return FVector2D(CanvasOrigin.X, CanvasOrigin.Y);
}

float UCubismModelComponent::GetPixelsPerUnit() const
{
	if (!RawModel)
	{
		// Never return zero: callers divide by this value.
		return 100.0f;
	}

	float PixelsPerUnit = 100.0f;
	csmVector2 CanvasSize, CanvasOrigin;

	csmReadCanvasInfo(RawModel, &CanvasSize, &CanvasOrigin, &PixelsPerUnit);

	return PixelsPerUnit > 0.0f ? PixelsPerUnit : 100.0f;
}

////

int32 UCubismModelComponent::GetDrawableCount() const
{
	return RawModel ? FMath::Max(csmGetDrawableCount(RawModel), 0) : 0;
}

FString UCubismModelComponent::GetDrawableId(const int32 DrawableIndex) const
{
	if (!RawModel || DrawableIndex < 0 || DrawableIndex >= GetDrawableCount())
	{
		return FString();
	}

	const char* DrawableId = csmGetDrawableIds(RawModel)[DrawableIndex];

	return FString(UTF8_TO_TCHAR(DrawableId));
}

int32 UCubismModelComponent::GetDrawableIndex(const FString DrawableId) const
{
	if (!DrawableIndices.Contains(DrawableId))
	{
		return -1;
	}

	return DrawableIndices[DrawableId];
}

UCubismDrawableComponent* UCubismModelComponent::GetDrawable(const int32 DrawableIndex) const
{
	return Drawables.IsValidIndex(DrawableIndex)? Drawables[DrawableIndex] : nullptr;
}

UCubismDrawableComponent* UCubismModelComponent::GetDrawable(const FString DrawableId) const
{
	return GetDrawable(GetDrawableIndex(DrawableId));
}

////

int32 UCubismModelComponent::GetParameterCount() const
{
	return RawModel ? FMath::Max(csmGetParameterCount(RawModel), 0) : 0;
}

FString UCubismModelComponent::GetParameterId(const int32 ParameterIndex) const
{
	if (NonNativeParameterIds.Contains(ParameterIndex))
	{
		return NonNativeParameterIds[ParameterIndex];
	}

	if (!RawModel || ParameterIndex < 0 || ParameterIndex >= GetParameterCount())
	{
		return FString();
	}

	const char* ParameterId = csmGetParameterIds(RawModel)[ParameterIndex];

	return FString(UTF8_TO_TCHAR(ParameterId));
}

int32 UCubismModelComponent::GetParameterIndex(const FString ParameterId)
{
	if (ParameterId.IsEmpty())
	{
		return -1;
	}

	if (const int32* FoundIndex = ParameterIndices.Find(ParameterId))
	{
		return *FoundIndex;
	}

	// Parameters that are not part of the model are created on demand (e.g. for pose parts and motion curves).
	if (!RawModel)
	{
		return -1;
	}

	AddParameter(ParameterId);

	return ParameterIndices[ParameterId];
}

UCubismParameterComponent* UCubismModelComponent::GetParameter(const int32 ParameterIndex) const
{
	return Parameters.IsValidIndex(ParameterIndex)? Parameters[ParameterIndex] : nullptr;
}

UCubismParameterComponent* UCubismModelComponent::GetParameter(const FString ParameterId)
{
	const int32 ParameterIndex = GetParameterIndex(ParameterId);

	return GetParameter(ParameterIndex);
}

////

int32 UCubismModelComponent::GetPartCount() const
{
	return RawModel ? FMath::Max(csmGetPartCount(RawModel), 0) : 0;
}

FString UCubismModelComponent::GetPartId(const int32 PartIndex) const
{
	if (NonNativePartIds.Contains(PartIndex))
	{
		return NonNativePartIds[PartIndex];
	}

	if (!RawModel || PartIndex < 0 || PartIndex >= GetPartCount())
	{
		return FString();
	}

	const char* PartId = csmGetPartIds(RawModel)[PartIndex];

	return FString(UTF8_TO_TCHAR(PartId));
}

int32 UCubismModelComponent::GetPartIndex(const FString PartId)
{
	if (PartId.IsEmpty())
	{
		return -1;
	}

	if (const int32* FoundIndex = PartIndices.Find(PartId))
	{
		return *FoundIndex;
	}

	if (!RawModel)
	{
		return -1;
	}

	AddPart(PartId);

	return PartIndices[PartId];
}

UCubismPartComponent* UCubismModelComponent::GetPart(const int32 PartIndex) const
{
	return Parts.IsValidIndex(PartIndex)? Parts[PartIndex] : nullptr;
}

UCubismPartComponent* UCubismModelComponent::GetPart(const FString PartId)
{
	const int32 PartIndex = GetPartIndex(PartId);

	return GetPart(PartIndex);
}

////

ECubismParameterType UCubismModelComponent::GetParameterType(const int32 ParameterIndex) const
{
	if (!RawModel || NonNativeParameterIds.Contains(ParameterIndex) || ParameterIndex < 0 || ParameterIndex >= GetParameterCount())
	{
		return ECubismParameterType::Normal;
	}

	return (ECubismParameterType) csmGetParameterTypes(RawModel)[ParameterIndex];
}

float UCubismModelComponent::GetParameterMinimumValue(const int32 ParameterIndex) const
{
	if (!RawModel || NonNativeParameterIds.Contains(ParameterIndex) || ParameterIndex < 0 || ParameterIndex >= GetParameterCount())
	{
		return std::numeric_limits<float>::quiet_NaN();
	}

	return csmGetParameterMinimumValues(RawModel)[ParameterIndex];
}

float UCubismModelComponent::GetParameterMaximumValue(const int32 ParameterIndex) const
{
	if (!RawModel || NonNativeParameterIds.Contains(ParameterIndex) || ParameterIndex < 0 || ParameterIndex >= GetParameterCount())
	{
		return std::numeric_limits<float>::quiet_NaN();
	}

	return csmGetParameterMaximumValues(RawModel)[ParameterIndex];
}

float UCubismModelComponent::GetParameterDefaultValue(const int32 ParameterIndex) const
{
	if (!RawModel || NonNativeParameterIds.Contains(ParameterIndex) || ParameterIndex < 0 || ParameterIndex >= GetParameterCount())
	{
		return 0.0f;
	}

	return csmGetParameterDefaultValues(RawModel)[ParameterIndex];
}

float UCubismModelComponent::GetParameterValue(const int32 ParameterIndex) const
{
	if (const float* NonNativeValue = NonNativeParameterValues.Find(ParameterIndex))
	{
		return *NonNativeValue;
	}

	if (!RawModel || ParameterIndex < 0 || ParameterIndex >= GetParameterCount())
	{
		return 0.0f;
	}

	return csmGetParameterValues(RawModel)[ParameterIndex];
}

void UCubismModelComponent::SetParameterValue(const int32 ParameterIndex, const float Value)
{
	if (float* NonNativeValue = NonNativeParameterValues.Find(ParameterIndex))
	{
		*NonNativeValue = Value;
		return;
	}

	if (!RawModel || ParameterIndex < 0 || ParameterIndex >= GetParameterCount())
	{
		return;
	}

	float ValueToSet = Value;
	if (UCubismParameterComponent* P = GetParameter(ParameterIndex))
	{
		ValueToSet = P->IsRepeat()
			? P->GetParameterRepeatValue(Value)
			: P->GetParameterClampValue(Value);
		P->Value = ValueToSet;
	}

	csmGetParameterValues(RawModel)[ParameterIndex] = ValueToSet;
}

int32 UCubismModelComponent::GetParameterKeyCount(const int32 ParameterIndex) const
{
	if (!RawModel || ParameterIndex < 0 || ParameterIndex >= GetParameterCount())
	{
		return 0;
	}

	return csmGetParameterKeyCounts(RawModel)[ParameterIndex];
}

const float* UCubismModelComponent::GetParameterKeyValue(const int32 ParameterIndex) const
{
	if (!RawModel || ParameterIndex < 0 || ParameterIndex >= GetParameterCount())
	{
		return nullptr;
	}

	return csmGetParameterKeyValues(RawModel)[ParameterIndex];
}

void UCubismModelComponent::AddParameter(const FString ParameterId)
{
	const int32 ParameterIndex = GetParameterCount() + NonNativeParameterIds.Num();

	ParameterIndices.Add(ParameterId, ParameterIndex);
	NonNativeParameterIds.Add(ParameterIndex, ParameterId);
	NonNativeParameterValues.Add(ParameterIndex, 0.0f);

	const FName ComponentName = MakeUniqueObjectName(this, UCubismParameterComponent::StaticClass(), FName(*ParameterId));
	UCubismParameterComponent* Parameter = NewObject<UCubismParameterComponent>(this, ComponentName, RF_Transactional);

	Parameter->Index = ParameterIndex;

	if (GetWorld())
	{
		Parameter->RegisterComponent();
	}

	Parameter->Setup(this);

	// Keep the array dense: the index of a parameter is its position in the array.
	if (Parameters.Num() <= ParameterIndex)
	{
		Parameters.SetNum(ParameterIndex + 1);
	}
	Parameters[ParameterIndex] = Parameter;
}

////

float UCubismModelComponent::GetPartOpacity(const int32 PartIndex) const
{
	if (const float* NonNativeOpacity = NonNativePartOpacities.Find(PartIndex))
	{
		return *NonNativeOpacity;
	}

	if (!RawModel || PartIndex < 0 || PartIndex >= GetPartCount())
	{
		return 1.0f;
	}

	return csmGetPartOpacities(RawModel)[PartIndex];
}

void UCubismModelComponent::SetPartOpacity(const int32 PartIndex, const float InOpacity)
{
	if (float* NonNativeOpacity = NonNativePartOpacities.Find(PartIndex))
	{
		*NonNativeOpacity = InOpacity;
		return;
	}

	if (!RawModel || PartIndex < 0 || PartIndex >= GetPartCount())
	{
		return;
	}

	csmGetPartOpacities(RawModel)[PartIndex] = InOpacity;
}

int UCubismModelComponent::GetPartParentPartIndex(const int32 PartIndex) const
{
	if (!RawModel || PartIndex < 0 || PartIndex >= GetPartCount())
	{
		return -1;
	}

	return csmGetPartParentPartIndices(RawModel)[PartIndex];
}

void UCubismModelComponent::AddPart(const FString PartId)
{
	const int32 PartIndex = GetPartCount() + NonNativePartIds.Num();

	PartIndices.Add(PartId, PartIndex);
	NonNativePartIds.Add(PartIndex, PartId);
	NonNativePartOpacities.Add(PartIndex, 1.0f);

	const FName ComponentName = MakeUniqueObjectName(this, UCubismPartComponent::StaticClass(), FName(*PartId));
	UCubismPartComponent* Part = NewObject<UCubismPartComponent>(this, ComponentName, RF_Transactional);

	Part->Index = PartIndex;

	if (GetWorld())
	{
		Part->RegisterComponent();
	}

	Part->Setup(this);

	if (Parts.Num() <= PartIndex)
	{
		Parts.SetNum(PartIndex + 1);
	}
	Parts[PartIndex] = Part;
}

void UCubismModelComponent::SetParameterValueRaw(const int32 ParameterIndex, const float Value)
{
	if (NonNativeParameterValues.Contains(ParameterIndex))
	{
		NonNativeParameterValues[ParameterIndex] = Value;
		return;
	}
	check(0 <= ParameterIndex && ParameterIndex < GetParameterCount());
	csmGetParameterValues(RawModel)[ParameterIndex] = Value;
}
////

ECubismDrawableBlendMode UCubismModelComponent::GetDrawableBlendMode(const int32 DrawableIndex) const
{
	if (!RawModel)
	{
		return ECubismDrawableBlendMode::Normal;
	}

	const csmFlags ConstantFlags = csmGetDrawableConstantFlags(RawModel)[DrawableIndex];

	if ((ConstantFlags & csmBlendAdditive) == csmBlendAdditive)
	{
		return ECubismDrawableBlendMode::Additive;
	}
	else if ((ConstantFlags & csmBlendMultiplicative) == csmBlendMultiplicative)
	{
		return ECubismDrawableBlendMode::Multiplicative;
	}
	else
	{
		return ECubismDrawableBlendMode::Normal;
	}
}

bool UCubismModelComponent::GetDrawableIsTwoSided(const int32 DrawableIndex) const
{
	if (!RawModel)
	{
		return false;
	}

	const csmFlags ConstantFlags = csmGetDrawableConstantFlags(RawModel)[DrawableIndex];

	return (ConstantFlags & csmIsDoubleSided) == csmIsDoubleSided;
}

bool UCubismModelComponent::GetDrawableInvertedMask(const int32 DrawableIndex) const
{
	if (!RawModel)
	{
		return false;
	}

	const csmFlags ConstantFlags = csmGetDrawableConstantFlags(RawModel)[DrawableIndex];

	return (ConstantFlags & csmIsInvertedMask) == csmIsInvertedMask;
}

bool UCubismModelComponent::GetDrawableDynamicFlagIsVisible(const int32 DrawableIndex) const
{
	if (!RawModel)
	{
		return false;
	}

	const csmFlags DynamicFlags = csmGetDrawableDynamicFlags(RawModel)[DrawableIndex];

	return (DynamicFlags & csmIsVisible) == csmIsVisible;
}

bool UCubismModelComponent::GetDrawableDynamicFlagVisibilityDidChange(const int32 DrawableIndex) const
{
	if (!RawModel)
	{
		return false;
	}

	const csmFlags DynamicFlags = csmGetDrawableDynamicFlags(RawModel)[DrawableIndex];

	return (DynamicFlags & csmVisibilityDidChange) == csmVisibilityDidChange;
}

bool UCubismModelComponent::GetDrawableDynamicFlagOpacityDidChange(const int32 DrawableIndex) const
{
	if (!RawModel)
	{
		return false;
	}

	const csmFlags DynamicFlags = csmGetDrawableDynamicFlags(RawModel)[DrawableIndex];

	return (DynamicFlags & csmOpacityDidChange) == csmOpacityDidChange;
}

bool UCubismModelComponent::GetDrawableDynamicFlagDrawOrderDidChange(const int32 DrawableIndex) const
{
	if (!RawModel)
	{
		return false;
	}

	const csmFlags DynamicFlags = csmGetDrawableDynamicFlags(RawModel)[DrawableIndex];

	return (DynamicFlags & csmDrawOrderDidChange) == csmDrawOrderDidChange;
}

bool UCubismModelComponent::GetDrawableDynamicFlagRenderOrderDidChange(const int32 DrawableIndex) const
{
	if (!RawModel)
	{
		return false;
	}

	const csmFlags DynamicFlags = csmGetDrawableDynamicFlags(RawModel)[DrawableIndex];

	return (DynamicFlags & csmRenderOrderDidChange) == csmRenderOrderDidChange;
}

bool UCubismModelComponent::GetDrawableDynamicFlagVertexPositionsDidChange(const int32 DrawableIndex) const
{
	if (!RawModel)
	{
		return false;
	}

	const csmFlags DynamicFlags = csmGetDrawableDynamicFlags(RawModel)[DrawableIndex];

	return (DynamicFlags & csmVertexPositionsDidChange) == csmVertexPositionsDidChange;
}

bool UCubismModelComponent::GetDrawableDynamicFlagBlendColorDidChange(const int32 DrawableIndex) const
{
	if (!RawModel)
	{
		return false;
	}

	const csmFlags DynamicFlags = csmGetDrawableDynamicFlags(RawModel)[DrawableIndex];

	return (DynamicFlags & csmBlendColorDidChange) == csmBlendColorDidChange;
}

int32 UCubismModelComponent::GetDrawableTextureIndex(const int32 DrawableIndex) const
{
	return RawModel ? csmGetDrawableTextureIndices(RawModel)[DrawableIndex] : 0;
}

int32 UCubismModelComponent::GetDrawableDrawOrder(const int32 DrawableIndex) const
{
	return RawModel ? csmGetDrawableDrawOrders(RawModel)[DrawableIndex] : 0;
}

int32 UCubismModelComponent::GetDrawableRenderOrder(const int32 DrawableIndex) const
{
	return RawModel ? csmGetDrawableRenderOrders(RawModel)[DrawableIndex] : 0;
}

float UCubismModelComponent::GetDrawableOpacity(const int32 DrawableIndex) const
{
	return RawModel ? csmGetDrawableOpacities(RawModel)[DrawableIndex] : 1.0f;
}

int32 UCubismModelComponent::GetDrawableMaskCount(const int32 DrawableIndex) const
{
	return RawModel ? csmGetDrawableMaskCounts(RawModel)[DrawableIndex] : 0;
}

const int32* UCubismModelComponent::GetDrawableMask(const int32 DrawableIndex) const
{
	return RawModel ? csmGetDrawableMasks(RawModel)[DrawableIndex] : nullptr;
}

int32 UCubismModelComponent::GetDrawableVertexCount(const int32 DrawableIndex) const
{
	return RawModel ? csmGetDrawableVertexCounts(RawModel)[DrawableIndex] : 0;
}

const csmVector2* UCubismModelComponent::GetDrawableVertexPosition(const int32 DrawableIndex) const
{
	return RawModel ? csmGetDrawableVertexPositions(RawModel)[DrawableIndex] : nullptr;
}

const csmVector2* UCubismModelComponent::GetDrawableVertexUv(const int32 DrawableIndex) const
{
	return RawModel ? csmGetDrawableVertexUvs(RawModel)[DrawableIndex] : nullptr;
}

int32 UCubismModelComponent::GetDrawableVertexIndexCount(const int32 DrawableIndex) const
{
	return RawModel ? csmGetDrawableIndexCounts(RawModel)[DrawableIndex] : 0;
}

const uint16* UCubismModelComponent::GetDrawableVertexIndex(const int32 DrawableIndex) const
{
	return RawModel ? reinterpret_cast<const uint16*>(csmGetDrawableIndices(RawModel)[DrawableIndex]) : nullptr;
}

FLinearColor UCubismModelComponent::GetDrawableMultiplyColor(const int32 DrawableIndex) const
{
	if (!RawModel)
	{
		return FLinearColor::White;
	}

	const csmVector4 Color = csmGetDrawableMultiplyColors(RawModel)[DrawableIndex];
	return FLinearColor(Color.X, Color.Y, Color.Z, Color.W);
}

FLinearColor UCubismModelComponent::GetDrawableScreenColor(const int32 DrawableIndex) const
{
	if (!RawModel)
	{
		return FLinearColor::Black;
	}

	const csmVector4 Color = csmGetDrawableScreenColors(RawModel)[DrawableIndex];
	return FLinearColor(Color.X, Color.Y, Color.Z, Color.W);
}

int32 UCubismModelComponent::GetDrawableParentPartIndex(const int32 DrawableIndex) const
{
	return RawModel ? csmGetDrawableParentPartIndices(RawModel)[DrawableIndex] : -1;
}
////

// UObject interface
void UCubismModelComponent::PostLoad()
{
	Super::PostLoad();

	EnsureModelBuilt();
}

void UCubismModelComponent::BeginDestroy()
{
	// OnComponentDestroyed is not guaranteed to run (e.g. editor shutdown), make sure the raw model does not leak.
	if (RawModel)
	{
		FMemory::Free(RawModel);
		RawModel = nullptr;
	}

	Super::BeginDestroy();
}

#if WITH_EDITOR
void UCubismModelComponent::PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent)
{
	Super::PostEditChangeProperty(PropertyChangedEvent);

	const FName PropertyName = PropertyChangedEvent.GetPropertyName();

	if (PropertyName == GET_MEMBER_NAME_CHECKED(UCubismModelComponent, bRenderInWorldSpace))
	{
		SetVisibility(bRenderInWorldSpace, true);
	}
	else if (PropertyName == GET_MEMBER_NAME_CHECKED(UCubismModelComponent, Moc))
	{
		Setup();
	}
	else if (
		PropertyName == GET_MEMBER_NAME_CHECKED(UCubismModelComponent, PoseJson) ||
		PropertyName == GET_MEMBER_NAME_CHECKED(UCubismModelComponent, MotionJsons) ||
		PropertyName == GET_MEMBER_NAME_CHECKED(UCubismModelComponent, ExpressionJsons) ||
		PropertyName == GET_MEMBER_NAME_CHECKED(UCubismModelComponent, PhysicsJson))
	{
		if (EnsureModelBuilt())
		{
			ComponentSetup();
		}
	}
	else if (PropertyName == GET_MEMBER_NAME_CHECKED(UCubismModelComponent, UserDataJson))
	{
		const FCubismUserDataEntry* UserDataEntry = UserDataJson ? UserDataJson->Data.Find(ECubismUserDataTargetType::ArtMesh) : nullptr;

		for (const TObjectPtr<UCubismDrawableComponent>& Drawable : Drawables)
		{
			if (!IsValid(Drawable))
			{
				continue;
			}

			const FString* Tag = UserDataEntry ? UserDataEntry->Tags.Find(Drawable->Id) : nullptr;

			Drawable->UserDataTag = Tag ? *Tag : TEXT("");
		}
	}
}
#endif
// End of UObject interface

// UActorComponent interface
void UCubismModelComponent::OnComponentCreated()
{
	Super::OnComponentCreated();

	EnsureModelBuilt();
}

void UCubismModelComponent::OnRegister()
{
	Super::OnRegister();

	// Loaded components have no world during PostLoad, so the helper components are created here.
	EnsureModelBuilt();
}

void UCubismModelComponent::BeginPlay()
{
	Super::BeginPlay();

	EnsureModelBuilt();
}

void UCubismModelComponent::PostApplyToComponent()
{
	Super::PostApplyToComponent();

	// Instance data (e.g. a Moc assigned on a placed Blueprint actor) is applied after OnComponentCreated.
	EnsureModelBuilt();
}

void UCubismModelComponent::ComponentSetup()
{
	if (!RawModel || !CanCreateComponents())
	{
		return;
	}

	AActor* Owner = GetOwner();

	// The order of creation matters because the components register tick dependencies on each other in Setup.
	{
		const bool bCreated = !IsValid(ParameterStore);
		UCubismParameterStoreComponent* Component = CreateHelperComponent(ParameterStore, TEXT("CubismParameterStore"));

		if (bCreated)
		{
			Component->RegisterComponent();
			if (Owner)
			{
				Owner->AddInstanceComponent(Component);
			}
		}
	}

	{
		const bool bCreated = !IsValid(Motion);
		UCubismMotionComponent* Component = CreateHelperComponent(Motion, TEXT("CubismMotion"));

		if (MotionJsons.Num() > 0 && Component->Jsons != MotionJsons)
		{
			Component->Jsons = MotionJsons;
		}

		if (bCreated)
		{
			Component->RegisterComponent();
			if (Owner)
			{
				Owner->AddInstanceComponent(Component);
			}
		}
	}

	{
		const bool bCreated = !IsValid(Pose);
		UCubismPoseComponent* Component = CreateHelperComponent(Pose, TEXT("CubismPose"));

		const bool bJsonChanged = PoseJson && Component->Json != PoseJson;

		if (bJsonChanged)
		{
			Component->Json = PoseJson;
		}

		if (bCreated)
		{
			Component->RegisterComponent();
			if (Owner)
			{
				Owner->AddInstanceComponent(Component);
			}
		}
		else if (bJsonChanged)
		{
			Component->Setup(this);
		}
	}

	{
		const bool bCreated = !IsValid(Expression);
		UCubismExpressionComponent* Component = CreateHelperComponent(Expression, TEXT("CubismExpression"));

		if (ExpressionJsons.Num() > 0 && Component->Jsons != ExpressionJsons)
		{
			Component->Jsons = ExpressionJsons;
		}

		if (bCreated)
		{
			Component->RegisterComponent();
			if (Owner)
			{
				Owner->AddInstanceComponent(Component);
			}
		}
	}

	{
		const bool bCreated = !IsValid(Physics);
		UCubismPhysicsComponent* Component = CreateHelperComponent(Physics, TEXT("CubismPhysics"));

		const bool bJsonChanged = PhysicsJson && Component->Json != PhysicsJson;

		if (bJsonChanged)
		{
			Component->Json = PhysicsJson;
		}

		if (bCreated)
		{
			Component->RegisterComponent();
			if (Owner)
			{
				Owner->AddInstanceComponent(Component);
			}
		}
		else if (bJsonChanged)
		{
			Component->Setup(this);
		}
	}

	{
		const bool bCreated = !IsValid(Renderer);
		UCubismRendererComponent* Component = CreateHelperComponent(Renderer, TEXT("CubismRenderer"));

		if (bCreated)
		{
			Component->RegisterComponent();
			if (Owner)
			{
				Owner->AddInstanceComponent(Component);
			}
		}
	}

	SetVisibility(bRenderInWorldSpace, true);
	if (GetOwner() && !GetOwner()->FindComponentByClass<UCubismUpdateControllerComponent>())
	{
		UCubismUpdateControllerComponent* Controller = NewObject<UCubismUpdateControllerComponent>(GetOwner(), UCubismUpdateControllerComponent::StaticClass(), TEXT("CubismUpdateController"));
		Controller->RegisterComponent();
		GetOwner()->AddInstanceComponent(Controller);
	}
}

void UCubismModelComponent::ComponentCleanup(const bool bDestroyHelperComponents)
{
	AActor* Owner = GetOwner();

	// The renderer caches the drawables in its junctions; they are about to be destroyed.
	if (IsValid(Renderer))
	{
		Renderer->Junctions.Empty();
		Renderer->NumMasks = 0;
	}

	for (const TObjectPtr<UCubismDrawableComponent>& Drawable : Drawables)
	{
		if (!IsValid(Drawable))
		{
			continue;
		}

		Drawable->DetachFromComponent(FDetachmentTransformRules::KeepRelativeTransform);
		if (Owner)
		{
			Owner->RemoveInstanceComponent(Drawable);
		}
		Drawable->DestroyComponent();
	}

	for (const TObjectPtr<UCubismParameterComponent>& Parameter : Parameters)
	{
		if (!IsValid(Parameter))
		{
			continue;
		}

		if (Owner)
		{
			Owner->RemoveInstanceComponent(Parameter);
		}
		Parameter->DestroyComponent();
	}

	for (const TObjectPtr<UCubismPartComponent>& Part : Parts)
	{
		if (!IsValid(Part))
		{
			continue;
		}

		if (Owner)
		{
			Owner->RemoveInstanceComponent(Part);
		}
		Part->DestroyComponent();
	}

	Drawables.Empty();
	Parameters.Empty();
	Parts.Empty();

	DrawableIndices.Empty();
	ParameterIndices.Empty();
	PartIndices.Empty();

	NonNativeParameterIds.Empty();
	NonNativeParameterValues.Empty();
	NonNativePartIds.Empty();
	NonNativePartOpacities.Empty();

	if (bDestroyHelperComponents)
	{
		// Only destroy the components this model created (their outer is the model). Components the user added to the actor are left alone.
		TArray<UActorComponent*> HelperComponents;
		HelperComponents.Add(Renderer);
		HelperComponents.Add(ParameterStore);
		HelperComponents.Add(Motion);
		HelperComponents.Add(Expression);
		HelperComponents.Add(Physics);
		HelperComponents.Add(Pose);
		HelperComponents.Add(EyeBlink);
		HelperComponents.Add(HarmonicMotion);
		HelperComponents.Add(LipSync);
		HelperComponents.Add(LookAt);

		for (UActorComponent* Component : HelperComponents)
		{
			if (!IsValid(Component) || Component->GetOuter() != this)
			{
				continue;
			}

			if (Owner)
			{
				Owner->RemoveInstanceComponent(Component);
			}
			Component->DestroyComponent();
		}

		Renderer = nullptr;
		ParameterStore = nullptr;
		Motion = nullptr;
		Expression = nullptr;
		Physics = nullptr;
		Pose = nullptr;
		EyeBlink = nullptr;
		HarmonicMotion = nullptr;
		LipSync = nullptr;
		LookAt = nullptr;
	}
}

void UCubismModelComponent::OnComponentDestroyed(bool bDestroyingHierarchy)
{
	ComponentCleanup(true);

	ReleaseRawModel();

	Super::OnComponentDestroyed(bDestroyingHierarchy);
}

#if WITH_EDITOR
void UCubismModelComponent::PostEditUndo()
{
	Super::PostEditUndo();

	Setup();
}
#endif

void UCubismModelComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	// When an update controller drives this actor it calls OnCubismUpdate in execution order instead.
	if (IsControlledByUpdateController() && UCubismUpdateControllerComponent::FindController(this))
	{
		return;
	}

	OnCubismUpdate(DeltaTime);
}

void UCubismModelComponent::OnCubismUpdate(float DeltaTime)
{
	if (!Moc)
	{
		// The moc was removed (e.g. force deleted); the raw model references its memory and must not be updated anymore.
		if (RawModel)
		{
			ComponentCleanup(false);
			ReleaseRawModel();
		}

		return;
	}

	if (!RawModel || Drawables.Num() == 0 || BuiltMoc != Moc)
	{
		// Lazy build for models whose moc was assigned or changed at runtime (e.g. from Blueprint).
		if (!EnsureModelBuilt())
		{
			return;
		}
	}
	if (RawModel)
	{
		// Clear the "did change" flags of the previous frame first so that the drawables,
		// which tick after the model, see the changes made by this update.
		csmResetDrawableDynamicFlags(RawModel);

		csmUpdateModel(RawModel);
	}
}

int32 UCubismModelComponent::GetExecutionOrder() const
{
	return CUBISM_EXECUTION_ORDER_MODEL;
}
// End of UActorComponent interface
